#!/bin/bash
echo "What is the name of the project?  This project will also be created under this name on Github."
read project

echo "What does this project do?"
read projectDesc

echo "What is the hostname of the project's API?"
read projectHost

echo "What is your GitHub username?"
read username

curl --silent -u "$username" https://api.github.com/user/repos -d "{\"name\":\"$project\"}" >/dev/null

git clone git@github.com:Emblem21/janus-prototype $project
cd $project
rm -fr .git
git init

echo "What is your database host?"
read dbHost
echo "What is your database username?"
read dbUser
echo "What is your database password?"
read -s dbPass

echo "Generating SSL cert for local Nginx..."
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/$project.key -out /etc/nginx/ssl/$project.crt

./install.js $project $username $projectDesc $projectHost $dbHost $dbUser $dbPass

npm install

rm install.js
rm new

git add .
git commit -m "Boilerplate commit"
git remote add origin git@github.com:$username/$project.git
git push -u origin master
git checkout -b develop
git merge master
git push -u origin develop
git checkout develop

echo ""
echo "================================================================================"
echo "$project has been successfully made.  Move to the directory"
echo "(cd $project) and run your server with:"
echo "================================================================================"
echo "npm run dev"
echo "================================================================================"