#!/bin/bash
echo "What is the name of the project?  This project will also be created under this name on Github."
read project

echo "What is your GitHub username?"
read username

echo "What is the hostname of the project's API?"
read projectHost


#curl --silent -u "$username" https://api.github.com/user/repos -d "{\"name\":\"$project\"}" >/dev/null

#git clone git@github.com:Emblem21/janus-prototype $project
#cd $project
#rm -fr .git
#git init

echo "What is your database host?"
read dbHost
echo "What is your database username?"
read dbUser
echo "What is your database password?"
read -s dbPass

sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/$project.key -out /etc/nginx/ssl/project.crt

./install.js $project $username $projectHost $dbHost $dbUser $dbPass

#git add .
#git commit -m "Boilerplate commit"
#git remote add origin git@github.com:$username/$project.git
#git push -u origin master
#git checkout -b develop
#git merge master
#git push -u origin develop
#git checkout develop

echo ""
echo "================================================================================"
echo "$project has been successfully made.  Your local checkout is in the develop branch."
echo "When you are ready to release your package, push all your changes to develop," 
echo "then follow these instructions:"
echo "================================================================================"
echo "./release"
echo "================================================================================"

